### ISSUE TITLE
(GLR) Real type issue

### ISSUE THREAD

**Issue by vollmersj** [tlienart/AnalyticalEngine.jl#12]
This snipplet throws an error

```julia
using RDatasets
using AnalyticalEngine
y=convert(Array{Float64},boston[:MedV]);
X=convert(Array{Float64,2},boston[[:LStat,:PTRatio,:Dis]]);
linReg=AnalyticalEngine.LinearRegression()
AnalyticalEngine.fit!(linReg,X,y)
```

> 
> MethodError: Cannot `convert` an object of type Array{Float64,1} to an object of type Union{AbstractArray{Real,1}, Void}
> This may have arisen from a call to the constructor Union{AbstractArray{Real,1}, Void}(...),
> since type constructors fall back to convert methods.
> 
> Stacktrace:
>  [1] #fit!#14(::String, ::Array{Any,1}, ::Function, ::AnalyticalEngine.GeneralizedLinearRegression, ::Array{Float64,2}, ::Array{Float64,1}) at /Applications/JuliaPro-0.6.2.1.app/Contents/Resources/pkgs-0.6.2.1/v0.6/AnalyticalEngine/src/supervised/glr-fit.jl:26
>  [2] fit!(::AnalyticalEngine.GeneralizedLinearRegression, ::Array{Float64,2}, ::Array{Float64,1}) at /Applications/JuliaPro-0.6.2.1.app/Contents/Resources/pkgs-0.6.2.1/v0.6/AnalyticalEngine/src/supervised/glr-fit.jl:10
>  [3] include_string(::String, ::String) at ./loading.jl:522

**Comment by tlienart** [comment]
This works for me (could you try? and if it works close?)

Maybe first do:

```julia
Pkg.checkout("AnalyticalEngine")
```

then

```julia
using AnalyticalEngine
import RDatasets: dataset

boston = dataset("MASS", "boston")
y = convert(Array, boston[:MedV])
X = convert(Array, boston[[:LStat, :PTRatio, :Dis]])

lr = LinearRegression()
fit!(lr, X, y)

RSS = sum((y - predict(lr, X)).^2)
TSS = sum((y-mean(y)).^2)
R2 = 1 - RSS/TSS
```

This gives me around `0.62`.  

**Side note** `import RDatasets` here so that the `fit!` from `AnalyticalEngine` doesn't conflict.

* `RDatasets` reexports `DataFrame`
* `DataFrame` reexports `StatsBase` 
* `StatsBase` defines `fit!` and exports it

so in some future we may want to extend `StatsBase`, not sure. Will open another issue for this --> #13.
